rock: Don't link mtk_agpsd to v32 libssl & libcrypto
* It doesn't seem to need it anymore,
  and linking with v32 libssl & libcrypto was
  causing build failed: use libssl & libcrypto instead.

error: vendor/xiaomi/rock/Android.bp:30941:1:
"mtk_agpsd" depends on undefined module "libcrypto-v32".
Or did you mean ["libcrypto-v33"]?

Co-Authored-By: Woomymy <woomy@woomy.be>
Co-Authored-By: xyzuniverse <dev.xyzuniverse@gmail.com>
Signed-off-by: Shakib <dev@shakib.my.id>